# WEB PROPERTIES
server:
  port: 5008

# SPRING
spring:
  # DATASOURCE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://192.168.1.110:3306/shangair?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false'
    username: root
    password: admin@123

  jpa:
    show-sql: false

kafka:
  broker-list: HighPressData01:9092,HighPressData02:9092,HighPressData03:9092
  zk-connect: HighPressData01:2181,HighPressData02:2181,HighPressData03:2181
  raw-topic: shangair_rawdata
  data-topic: shangair_metrics

hbase:
  zk-quorum: 192.168.1.111,192.168.1.112,192.168.1.113
  zk-port: 2181
  data-table: tcloud:shangair_metrics

redis:
  host: 192.168.1.113
  port: 6379
  password:
  database: 0
  channel: sa_channel
  equipment-info-key: 'sa:summery:'
  equipment-detail-key: 'sa:detail:'