# WEB PROPERTIES
server:
  port: 5008

# SPRING
spring:
  # DATASOURCE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://192.168.1.51:3306/shangair?useUnicode=true&characterEncoding=UTF-8'
    username: root
    password: 123456

  jpa:
    show-sql: true


kafka:
  broker-list: xg153:9092,xg154:9092,xg155:9092
  zk-connect: xg153:2181,xg154:2181,xg155:2181
  raw-topic: shangair_rawdata
  data-topic: shangair_metrics

hbase:
  zk-quorum: 192.168.1.153,192.168.1.154,192.168.1.155
  zk-port: 2181
  data-table: tcloud:shangair_metrics

redis:
  host: 192.168.1.156
  port: 6379
  password:
  database: 0
  channel: sa_channel